In [69]:
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from TransformerNetwork import * 
from t2v import *

In [64]:
# hyperparameter
window_size = 5
enc_seq_len = window_size
dec_seq_len = 2
output_sequence_length = 1

dim_val = 5 # input data # features
dim_attn = 8
lr = 0.002
epochs = 1

n_heads = 2 

n_decoder_layers = 2
n_encoder_layers = 2

batch_size = 15

# time to vec
time_embed_size = 2

In [75]:
df = pd.read_csv("cleaned_data")
X = df.iloc[:,1:]
y = df["Close"]
x,y = X.to_numpy(),y.to_numpy()

In [48]:
def sliding_window(x,y, window_size):
    xx, yy = [], []
    for i in range(window_size,len(x)):
        xx.append(x[i-window_size:i])
        yy.append(y[i])
    xx, yy = np.array(xx), np.array(yy)
    return xx, yy

In [49]:
x,y = sliding_window(x,y,window_size = 5)

(37675, 1507)

In [58]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [114]:
sinact = SineActivation(5,2)
q = x_train[:3,:,:].astype(np.float32)
q =torch.from_numpy(q)
torch.reshape(q,(15,5))
a = sinact(q)
a.reshape()

In [116]:
q = x_train[:3,:,:].astype(np.float32)
q =torch.from_numpy(q)
a = torch.reshape(q,(15,5))
torch.reshape(a,(3,5,5))

tensor([[[0.5449, 0.5982, 0.5188, 0.6711, 0.1278],
         [0.4387, 0.5035, 0.4878, 0.5961, 0.1032],
         [0.5128, 0.5469, 0.5493, 0.5643, 0.0803],
         [0.4739, 0.4797, 0.2901, 0.4386, 0.2245],
         [0.3897, 0.4045, 0.4756, 0.5881, 0.0595]],

        [[0.4101, 0.4287, 0.2926, 0.4373, 0.2394],
         [0.3516, 0.3888, 0.4232, 0.5247, 0.0373],
         [0.3850, 0.4407, 0.3995, 0.4959, 0.1150],
         [0.4111, 0.4279, 0.3583, 0.5037, 0.1741],
         [0.3763, 0.4416, 0.3986, 0.5023, 0.0848]],

        [[0.3674, 0.4774, 0.3632, 0.5615, 0.2631],
         [0.4920, 0.5128, 0.5357, 0.5624, 0.0860],
         [0.4303, 0.4358, 0.4080, 0.5165, 0.0396],
         [0.3888, 0.4615, 0.4018, 0.5249, 0.1219],
         [0.3857, 0.3882, 0.3262, 0.4189, 0.2350]]])
tensor([[0.5449, 0.5982, 0.5188, 0.6711, 0.1278],
        [0.4387, 0.5035, 0.4878, 0.5961, 0.1032],
        [0.5128, 0.5469, 0.5493, 0.5643, 0.0803],
        [0.4739, 0.4797, 0.2901, 0.4386, 0.2245],
        [0.3897, 0.4045, 0.47

tensor([[[0.5449, 0.5982, 0.5188, 0.6711, 0.1278],
         [0.4387, 0.5035, 0.4878, 0.5961, 0.1032],
         [0.5128, 0.5469, 0.5493, 0.5643, 0.0803],
         [0.4739, 0.4797, 0.2901, 0.4386, 0.2245],
         [0.3897, 0.4045, 0.4756, 0.5881, 0.0595]],

        [[0.4101, 0.4287, 0.2926, 0.4373, 0.2394],
         [0.3516, 0.3888, 0.4232, 0.5247, 0.0373],
         [0.3850, 0.4407, 0.3995, 0.4959, 0.1150],
         [0.4111, 0.4279, 0.3583, 0.5037, 0.1741],
         [0.3763, 0.4416, 0.3986, 0.5023, 0.0848]],

        [[0.3674, 0.4774, 0.3632, 0.5615, 0.2631],
         [0.4920, 0.5128, 0.5357, 0.5624, 0.0860],
         [0.4303, 0.4358, 0.4080, 0.5165, 0.0396],
         [0.3888, 0.4615, 0.4018, 0.5249, 0.1219],
         [0.3857, 0.3882, 0.3262, 0.4189, 0.2350]]])